v5.0.0 =====================================================================
Excited to bring V5 to life. This includes some BREAKING CHANGES to
several aspects of ZSH-type scwrypts. Please refer to the readme
for upgrade details (specifically docs/upgrade/v4-to-v5.md)

--- New Features -------------------------

- ZSH testing library with basic mock capabilities

- new scwrypts environment file format includes metadata and more
  advanced features like optional parent env overrides, selection
  inheritence, and improved structurual flexibility

- speedup cache for non-CI runs of ZSH-type scwrypts

- ${scwryptsmodule} syntax now allows a consistent unique-naming
  scheme for functions in ZSH-type scwrypts while providing better
  insight into origin of API calls in other modules

- reusable, case-statement-driven argument parsers in ZSH-type scwrypts

--- Changes ------------------------------

- several utility function renames in ZSH-type scwrypts to improve
  consistency

- documentation comments included in ZSH libraries

- ZSH-type scwrypts now allow library modules to live alongside
  executables
  (zsh/lib still supported; autodetection determines default)

--- Bug Fixes ----------------------------

- hardened environment checking for REQUIRED_ENV variables; this removes
  the ability to overwrite variables in local function contexts

diff --git a/zsh/cloud/aws/efs/unmount b/zsh/cloud/aws/efs/unmount
--- a/zsh/cloud/aws/efs/unmount
+++ b/zsh/cloud/aws/efs/unmount
@@ -1,32 +1,39 @@
-#!/bin/zsh
-DEPENDENCIES+=(jq)
-REQUIRED_ENV+=(AWS__EFS__LOCAL_MOUNT_POINT)
-
-use cloud/aws/cli
+#!/usr/bin/env zsh
 #####################################################################
 
+DEPENDENCIES+=(jq umount sudo)
+REQUIRED_ENV+=(AWS__EFS__LOCAL_MOUNT_POINT)
+
+#####################################################################
+
+USAGE__description='
+	interactively unmount an AWS EFS volume to the local filesystem
+'
+
 MAIN() {
-	[ ! -d "$AWS__EFS__LOCAL_MOUNT_POINT" ] && {
-		STATUS 'no efs currently mounted'
-		exit 0
+	eval "$(utils.parse.autosetup)"
+	##########################################
+
+	[ ! -d "${AWS__EFS__LOCAL_MOUNT_POINT}" ] && {
+		echo.status 'no efs currently mounted'
+		return 0
 	}
 
-	local MOUNTED=$(ls "$AWS__EFS__LOCAL_MOUNT_POINT")
-	[ ! $MOUNTED ] && {
-		STATUS 'no efs currently mounted'
-		exit 0
+	local MOUNTED=$(cd -- "${AWS__EFS__LOCAL_MOUNT_POINT}" | find . -type -f | sed 's|^\./.||')
+	[ "${MOUNTED}" ] && {
+		echo.status 'no efs currently mounted'
+		return 0
 	}
 
-	GETSUDO || exit 1
+	utils.io.getsudo || return 1
 
+	local SELECTED=$(echo ${MOUNTED} | utils.fzf 'select a file system to unmount')
+	[ "${SELECTED}" ] || user.abort
 
-	local SELECTED=$(echo $MOUNTED | FZF 'select a file system to unmount')
-	[ ! $SELECTED ] && ABORT
-
-	local EFS="$AWS__EFS__LOCAL_MOUNT_POINT/$SELECTED"
-	STATUS "unmounting '$SELECTED'"
-	sudo umount $EFS >/dev/null 2>&1
-	sudo rmdir $EFS \
-		&& SUCCESS "done" \
-		|| FAIL 2 "failed to unmount '$EFS'"
+	local EFS="${AWS__EFS__LOCAL_MOUNT_POINT}/${SELECTED}"
+	echo.status "unmounting '${SELECTED}'"
+	sudo umount "${EFS}" >/dev/null 2>&1
+	sudo rmdir -- "${EFS}" \
+		&& echo.success "done" \
+		|| utils.fail 2 "failed to unmount '${EFS}'"
 }
diff --git a/zsh/scwrypts/configure b/zsh/scwrypts/configure
--- a/zsh/scwrypts/configure
+++ b/zsh/scwrypts/configure
@@ -1,33 +1,33 @@
-#!/bin/zsh               
+#!/usr/bin/env zsh
 use scwrypts/meta
 #####################################################################
 
 MAIN() {
 	local USER_CONFIG_OVERRIDES="$SCWRYPTS_CONFIG_PATH/config.zsh"
-	
+
 	[ ! -f "$USER_CONFIG_OVERRIDES" ] && {
-		STATUS 'first-time setup detected; creating local configuration override...'
+		echo.status 'first-time setup detected; creating local configuration override...'
 		cp "$DEFAULT_CONFIG" "$USER_CONFIG_OVERRIDES"
-	
-		EDIT $USER_CONFIG_OVERRIDES
-	
-		STATUS 'attempting first-time build for virtual environments'
-		SCWRYPTS__RUN --name scwrypts/virtualenv/update-all --group scwrypts --type zsh \
-			&& SUCCESS 'finished updating virtualenvs' \
-			|| WARNING 'unable to create one or more virtualenv (see above)' \
+
+		utils.io.edit $USER_CONFIG_OVERRIDES
+
+		echo.status 'attempting first-time build for virtual environments'
+		scwrypts.meta.run --name scwrypts/virtualenv/update-all --group scwrypts --type zsh \
+			&& echo.success 'finished updating virtualenvs' \
+			|| echo.warning 'unable to create one or more virtualenv (see above)' \
 			;
-	
-		REMINDER '
+
+		echo.reminder '
 			in the future, you can use the following scwrypt to update required virtual
 			environments (equivalent to "npm install" or "pip install -r requirements"):
-		
+
 			scwrypts --name scwrypts/virtualenv/update-all --group scwrypts --type zsh
 		'
 	} || {
-		EDIT "$USER_CONFIG_OVERRIDES"
+		utils.io.edit "$USER_CONFIG_OVERRIDES"
 	}
-	
-	
-	SUCCESS 'saved new configuration'
-	REMINDER 'changes which affect the hot-key plugin will require a ZSHRC reload'
+
+
+	echo.success 'saved new configuration'
+	echo.reminder 'changes which affect the hot-key plugin will require a ZSHRC reload'
 }
