v4.0.0 =====================================================================
Big day! V4 is finally live. This INCLUDES some BREAKING CHANGES to ZSH
TYPE scwrypts! Please refer to the readme for upgrade details
                     (more specifically docs/upgrade/v3-to-v4.md)

Upgrade is SUPER EASY, so please take the time to do so.

--- New Features ----------------------------------------------------

- zsh type scwrypts have an upgraded runstring to improve context setup
  and simplicity to the scwrypt-writer

- scwrypts now publishes the package (scwrypts) to PyPi; this provides a
  simple way to invoke scwrypts from python-based environments as well
  as the entire scwrypts python library suite

  pip install scwrypts

- scwrypts now publishes the package (scwrypts) to npm; this provides a
  simple way to invoke scwrypts from nodesjs environments

  npm install scwrypts

--- Bug Fixes -------------------------------------------------------

- scwrypts runner prompts which use the zshbuiltin "read" now
  appropriately read input from tty, pipe, files, and user input

- virtualenv refresh now loads and prepares the scwrypts virtual
  environments correctly

--- Changes ---------------------------------------------------------

- created the (-v, --log-level) scwrypts arguments as improvements of
  and replacements to the --verbose and --no-log flags
     - (-n) is now an alias for (--log-level 0)
     - (--no-log) is the same as (-n) for compatibility, but will be removed in 4.2

- zsh/lib/utils/io print functions now *interact with log-level* various
  log levels will now only display the appropriate console prints for
  the specified log level

- zsh/lib/utils/io:INFO has been renamed to DEBUG to align with
  log-level output; please use DEBUG for debug messages and REMINDER for
  important user messages

- created zsh/lib/utils/io:FZF_USER_INPUT as a *drop-in replacement* for
  the confusing FZF_HEAD and FZF_TAIL commands. Update by literally
  changing any instances of FZF_HEAD or FZF_TAIL with FZF_USER_INPUT
     - FZF_HEAD and FZF_TAIL will be removed in 4.2

- zsh/lib/utils/io:READ (and other zshbuiltin/read-based prompts) now
  accept a --force-user-input flag in case important checks should
  require an admin's approval. This flag will ensure that piped input
  and the `scwrypts -y` flag are ignored for the single prompt.

- zsh/lib/utils/color has been updated to use color names which match
  the ANSI color names

- zsh/hello-world has been reduced to a minimal example; this is to
  emphasize ease-of-use with v4

- zsh/sanity-check is a scwrypts/run testing helper and detailed
  starting reference (helpful since hello-world is now minimal)

- various refactor, updates, and improvements to the scwrypts runner

- migrated all zsh scwrypts and plugins to use v4 runner syntax
     - zsh
     - plugins/kubectl
     - plugins/ci

- refactored py/lib into py/lib/scwrypts (PyPi)

diff --git a/zsh/scwrypts/virtualenv/update-all b/zsh/scwrypts/virtualenv/update-all
--- a/zsh/scwrypts/virtualenv/update-all
+++ b/zsh/scwrypts/virtualenv/update-all
@@ -1,25 +1,21 @@
 #!/bin/zsh
-echo hey
-DEPENDENCIES+=()
-REQUIRED_ENV+=()
-
 use scwrypts/virtualenv
-
-CHECK_ENVIRONMENT
 #####################################################################
 
-STATUS 'beginning update for all environments'
-
-FAILED_COUNT=0
-
-for ENV_GROUP in ${SCWRYPTS_GROUPS[@]}
-do
-	for ENV_TYPE in ${AVAILABLE_VIRTUALENVS[@]}
+MAIN() {
+	STATUS 'beginning update for all environments'
+	
+	FAILED_COUNT=0
+	
+	for ENV_GROUP in ${SCWRYPTS_GROUPS[@]}
 	do
-		UPDATE_VIRTUALENV $ENV_GROUP $ENV_TYPE || ((FAILED_COUNT+=1))
+		for ENV_TYPE in ${AVAILABLE_VIRTUALENVS[@]}
+		do
+			UPDATE_VIRTUALENV $ENV_GROUP $ENV_TYPE || ((FAILED_COUNT+=1))
+		done
 	done
-done
-
-[[ $FAILED_COUNT -eq 0 ]] \
-	&& SUCCESS 'all environments up-to-date' \
-	|| FAIL $FAILED_COUNT "failed to update $FAILED_COUNT more environment(s)"
+	
+	[[ $FAILED_COUNT -eq 0 ]] \
+		&& SUCCESS 'all environments up-to-date' \
+		|| FAIL $FAILED_COUNT "failed to update $FAILED_COUNT more environment(s)"
+}
