v5.0.0 =====================================================================
Excited to bring V5 to life. This includes some BREAKING CHANGES to
several aspects of ZSH-type scwrypts. Please refer to the readme
for upgrade details (specifically docs/upgrade/v4-to-v5.md)

--- New Features -------------------------

- ZSH testing library with basic mock capabilities

- new scwrypts environment file format includes metadata and more
  advanced features like optional parent env overrides, selection
  inheritence, and improved structurual flexibility

- speedup cache for non-CI runs of ZSH-type scwrypts

- ${scwryptsmodule} syntax now allows a consistent unique-naming
  scheme for functions in ZSH-type scwrypts while providing better
  insight into origin of API calls in other modules

- reusable, case-statement-driven argument parsers in ZSH-type scwrypts

--- Changes ------------------------------

- several utility function renames in ZSH-type scwrypts to improve
  consistency

- documentation comments included in ZSH libraries

- ZSH-type scwrypts now allow library modules to live alongside
  executables
  (zsh/lib still supported; autodetection determines default)

--- Bug Fixes ----------------------------

- hardened environment checking for REQUIRED_ENV variables; this removes
  the ability to overwrite variables in local function contexts

diff --git a/zsh/scwrypts/virtualenv/update-all b/zsh/scwrypts/virtualenv/update-all
--- a/zsh/scwrypts/virtualenv/update-all
+++ b/zsh/scwrypts/virtualenv/update-all
@@ -1,21 +1,22 @@
-#!/bin/zsh
-use scwrypts/virtualenv
+#!/usr/bin/env zsh
+use scwrypts/virtualenv/update
 #####################################################################
 
 MAIN() {
-	STATUS 'beginning update for all environments'
-	
-	FAILED_COUNT=0
-	
-	for ENV_GROUP in ${SCWRYPTS_GROUPS[@]}
+	local ERRORS=0
+	local ENV_TYPE ENV_TYPE_COUNT=${#SCWRYPTS_VIRTUALENV__AVAILABLE_VIRTUALENVS[@]}
+
+	echo.status 'beginning update for all environments'
+	for ENV_TYPE in ${SCWRYPTS_VIRTUALENV__AVAILABLE_VIRTUALENVS[@]}
 	do
-		for ENV_TYPE in ${AVAILABLE_VIRTUALENVS[@]}
-		do
-			UPDATE_VIRTUALENV $ENV_GROUP $ENV_TYPE || ((FAILED_COUNT+=1))
-		done
+		scwrypts.virtualenv.update $ENV_TYPE \
+			&& echo.success "successfully updated '${ENV_TYPE}'" \
+			|| echo.error   "error updating '${ENV_TYPE}'" \
+			;
 	done
-	
-	[[ $FAILED_COUNT -eq 0 ]] \
-		&& SUCCESS 'all environments up-to-date' \
-		|| FAIL $FAILED_COUNT "failed to update $FAILED_COUNT more environment(s)"
+
+	[[ ${ERRORS} -eq 0 ]] \
+		&& echo.success "successfully updated ${ENV_TYPE_COUNT} / ${ENV_TYPE_COUNT} environment(s)" \
+		|| echo.error   "failed to update ${FAILED_COUNT} / ${ENV_TYPE_COUNT} environment(s)" \
+		;
 }
